#region Disk
Add-PartitionAccessPath
Add-PhysicalDisk
Clear-Disk
Connect-IscsiTarget
Connect-VirtualDisk
Convert-PhysicalDisk
Disconnect-IscsiTarget
Dismount-DiskImage
Format-Volume
Get-Disk
Get-DiskImage
Get-Partition
Get-PartitionSupportedSize
Get-PhysicalDisk
New-Volume
New-Partition
Remove-Partition
Remove-PartitionAccessPath
Remove-PhysicalDisk
Reset-PhysicalDisk
Resize-Partition
Repair-VirtualDisk
Repair-Volume
Set-Partition
Set-PhysicalDisk
Update-Disk
#endregion
#region Printing
Add-Printer
Add-PrinterDriver
Add-PrinterPort
Get-PrintConfiguration
Get-Printer
Get-PrinterDriver
Get-PrinterPort
Get-PrinterProperty
Get-PrintJob
Set-PrintConfiguration
Set-Printer
Rename-Printer
Remove-Printer
Remove-PrinterDriver
Remove-PrinterPort
Remove-PrintJob
Set-PrinterProperty
Resume-PrintJob


#endregion
#region Networking
Resolve-DnsName
Test-NetConnection

Add-VpnConnection
Add-VpnConnectionRoute
Add-VpnConnectionTriggerApplication
Add-VpnConnectionTriggerDnsConfiguration
Add-VpnConnectionTriggerTrustedNetwork
Clear-DnsClientCache
Copy-NetFirewallRule
Copy-NetIPsecMainModeCryptoSet
Copy-NetIPsecMainModeRule
Copy-NetIPsecPhase1AuthSet
Copy-NetIPsecPhase2AuthSet
Copy-NetIPsecQuickModeCryptoSet
Copy-NetIPsecRule
Disable-NetAdapter
Disable-NetAdapterBinding
Disable-NetAdapterChecksumOffload
Disable-NetAdapterEncapsulatedPacketTaskOffload
Disable-NetAdapterIPsecOffload
Disable-NetAdapterLso
Disable-NetAdapterPacketDirect
Disable-NetAdapterPowerManagement
Disable-NetAdapterQos
Disable-NetAdapterRdma
Disable-NetAdapterRsc
Disable-NetAdapterRss
Disable-NetAdapterSriov
Disable-NetAdapterUro
Disable-NetAdapterUso
Disable-NetAdapterVmq
Disable-NetFirewallRule
Disable-NetIPsecMainModeRule
Disable-NetIPsecRule
Enable-NetAdapter
Enable-NetAdapterBinding
Enable-NetAdapterChecksumOffload
Enable-NetAdapterEncapsulatedPacketTaskOffload
Enable-NetAdapterIPsecOffload
Enable-NetAdapterLso
Enable-NetAdapterPacketDirect
Enable-NetAdapterPowerManagement
Enable-NetAdapterQos
Enable-NetAdapterRdma
Enable-NetAdapterRsc
Enable-NetAdapterRss
Enable-NetAdapterSriov
Enable-NetAdapterUro
Enable-NetAdapterUso
Enable-NetFirewallRule
Enable-NetIPsecMainModeRule
Enable-NetIPsecRule
Find-NetIPsecRule
Find-NetRoute
Get-DnsClient
Get-DnsClientCache
Get-DnsClientServerAddress
Get-NetAdapter
Get-NetAdapterAdvancedProperty
Get-NetAdapterBinding
Get-NetAdapterHardwareInfo
Get-NetAdapterIPsecOffload
Get-NetAdapterLso
Get-NetAdapterPacketDirect
Get-NetAdapterPowerManagement
Get-NetAdapterQos
Get-NetAdapterRdma
Get-NetAdapterRsc
Get-NetAdapterRss
Get-NetAdapterSriov
Get-NetAdapterSriovVf
Get-NetAdapterStatistics
Get-NetAdapterUro
Get-NetAdapterUso
Get-NetFirewallAddressFilter
Get-NetFirewallApplicationFilter
Get-NetFirewallDynamicKeywordAddress
Get-NetFirewallInterfaceFilter
Get-NetFirewallInterfaceTypeFilter
Get-NetFirewallPortFilter
Get-NetFirewallProfile
Get-NetFirewallRule
Get-NetFirewallSecurityFilter
Get-NetFirewallServiceFilter
Get-NetFirewallSetting
Get-NetIPAddress
Get-NetIPConfiguration
Get-NetIPInterface
Get-NetIPsecDospSetting
Get-NetIPsecMainModeCryptoSet
Get-NetIPsecMainModeRule
Get-NetIPsecMainModeSA
Get-NetIPsecPhase1AuthSet
Get-NetIPsecPhase2AuthSet
Get-NetIPsecQuickModeCryptoSet
Get-NetIPsecQuickModeSA
Get-NetIPsecRule
Get-NetIPv4Protocol
Get-NetIPv6Protocol
Get-NetNeighbor
Get-NetRoute
Get-NetTCPConnection
Get-NetTCPSetting
Get-NetTeredoConfiguration
Get-NetTeredoState

#endregion
#region Services and Tasks
Disable-ScheduledTask
Enable-ScheduledTask
Export-ScheduledTask
Start-ScheduledTask
New-ScheduledTask
New-ScheduledTaskAction
New-ScheduledTaskPrincipal
New-ScheduledTaskSettingsSet
New-ScheduledTaskTrigger
Register-ScheduledTask
Get-ScheduledTask
Get-ScheduledTaskInfo
New-Service
Get-Service
Start-Service
Restart-Service
Stop-Service
Set-Service
Suspend-Service
Resume-Service
Remove-Service
New-ScheduledJobOption

#endregion
#region Client functionality
Block-SmbClientAccessToServer
Disconnect-NfsSession
Get-NfsClientConfiguration
Get-NfsSession

#endregion
#region Security
Get-Acl
Set-Acl
Add-LocalGroupMember
New-LocalGroup
New-LocalUser
Enable-LocalUser
Disable-LocalUser
Get-LocalGroup
Get-LocalGroupMember
Get-LocalUser
Rename-LocalGroup
Rename-LocalUser
Remove-LocalGroup
Remove-LocalGroupMember
Remove-LocalUser
Set-LocalGroup
Set-LocalUser

#endregion
#region sundry
Get-DisplayResolution # this is available in WinPS only!
Get-PlatformIdentifier
Get-ComputerInfo
Get-PnpDevice
Get-PnpDeviceProperty
Set-SystemPreferredUILanguage
Set-TimeZone

Test-Certificate
Export-Certificate
Export-PfxCertificate
Get-PfxData
New-SelfSignedCertificate

Get-SystemDriver

Rename-Computer

Out-GridView
Out-Printer

Show-Command

#endregion